/**
 * Regenerates `docs/tokens.md`.
 *
 * Run with `bun run docs`.
 *
 * The examples are produced by calling the generator, not written down — a
 * hand-maintained table of what a generator emits is wrong the first time
 * someone edits the generator and forgets the docs, and the whole point of
 * documenting the vocabulary is that it is trustworthy.
 *
 * The page is generated in full rather than spliced into a marked region, so
 * there is nothing in it a person is meant to hand-edit.
 */

import fs from 'node:fs'
import path from 'node:path'

import { DATE_EPOCH, TOKENS, sampleToken } from '../src/shared/generate'

const OUT = path.resolve(import.meta.dir, '../docs/tokens.md')

/** Keeps a long lorem paragraph from blowing the column width apart. */
function clip(text: string, max = 52): string {
  const single = text.replace(/\s+/g, ' ')
  return single.length > max ? `${single.slice(0, max - 1)}…` : single
}

function cell(text: string): string {
  return text.replace(/\|/g, '\\|')
}

const rows = TOKENS.map((entry) => {
  const args = entry.args ? `\`${entry.args}\`` : ''
  return `| \`${entry.token}\` | ${cell(entry.summary)} | ${args} | \`${cell(clip(sampleToken(entry.token)))}\` |`
})

const table = [
  '| Token | Produces | Arguments | Example |',
  '| --- | --- | --- | --- |',
  ...rows,
].join('\n')

const page = `<!-- Generated by \`bun run docs\` from src/shared/generate.ts. Do not edit. -->

# \`@fake\` tokens

Annotate a field in your own types and the generator produces that kind of value
for it:

\`\`\`ts
export type User = {
  /** @fake person.fullName */
  name: string
  /** @fake number.int({min: 1, max: 9999}) */
  id: number
}
\`\`\`

Arguments are JSON, braces included: \`number.int({min: 1, max: 10})\`.

This is the whole vocabulary — ${TOKENS.length} tokens, and there is no larger
set behind it. The names are shaped like [Faker](https://fakerjs.dev)'s so they
read the way you would guess, but nothing from that library is involved and only
what is listed here exists. Anything else warns, naming the closest match.

\`@faker\` is the original spelling of the tag and is still read, so existing
annotations keep working.

The **Example** column is produced by running the generator, so it is exactly
what you get — though values vary with the seed, and **Generate** rerolls them.

${table}

### \`date.*\` is relative to a fixed epoch, not to now

Every date token is offset from **${new Date(DATE_EPOCH).toISOString().slice(0, 10)}**,
not from the current time. Generation has to be reproducible — the same seed and
schema must give the same object every run, which a value read off the clock
cannot do.

So \`date.recent\` means "up to a week before the epoch", and it sits further in
the past the further real time moves from that date. Assert on ordering
(\`createdAt\` before \`updatedAt\`) or on the format; a test asserting a generated
timestamp is within the last hour will fail for reasons that have nothing to do
with the code under test.

## What unannotated fields produce

| Source | Produces |
| --- | --- |
| \`string\` | Lorem words. A bare string could be a name, a URL or a date; guessing wrong is worse than being obviously generic |
| \`number\` | A whole number. TypeScript has one numeric type, so an id, a count and a price extract identically, and \`"id": 839.05\` reads as broken data. Use \`@fake number.float\` for decimals |
| \`boolean\` | \`true\` or \`false\` |
| a union | One branch, chosen by the seed. The panel's **variant** control picks a specific one |
| an enum | One of its values — an enum is resolved *before* any \`@fake\` tag, so annotating one has no effect |
| \`string\` with a JSON Schema \`format\` | \`date-time\`, \`date\`, \`email\`, \`uri\` and \`uuid\` are honoured with no annotation needed |
| \`any\` / \`unknown\` | \`null\`, plus a warning naming the path. There is nothing to generate from, and inventing a shape would be worse |
| a recursive type | Stops at a depth cap, so a comment tree terminates |

## Seeing this list in place

- \`npx data-seed tokens\` prints it in your terminal, next to the source you are
  annotating.
- The tag button beside **Generate** in the panel shows it against the type you
  are seeding.
`

fs.mkdirSync(path.dirname(OUT), { recursive: true })
fs.writeFileSync(OUT, page, 'utf8')

console.log(`Wrote ${TOKENS.length} tokens to docs/tokens.md`)
